language: php

sudo: false

matrix:
  include:
  - php: 7.1
    env: STATIC_ANALYSIS=true VALIDATE_CODING_STYLE=true
  - php: 7.2
    env: STATIC_ANALYSIS=true VALIDATE_CODING_STYLE=true
  - php: 7.3
    env: STATIC_ANALYSIS=true VALIDATE_CODING_STYLE=true
  - php: 7.4
    env: STATIC_ANALYSIS=true VALIDATE_CODING_STYLE=true
  - php: master
    env: STATIC_ANALYSIS=true VALIDATE_CODING_STYLE=false
  allow_failures:
  - php: master
  fast_finish: true

cache:
  directories:
  - $HOME/.composer/cache

before_install:
- travis_retry composer self-update

install:
- travis_retry composer update --no-interaction --prefer-source

script:
- composer phpunit

after_script:
- if [ "$VALIDATE_CODING_STYLE" == "true" ]; then composer phpcs; fi
- if [ "$STATIC_ANALYSIS" == "true" ]; then composer phpstan; fi
